---
sudo: required

language: python

python:
  - "3.6"


addons:
  apt:
    packages:
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev

services:
  - docker

install:
  - docker build --no-cache -t dabelenda/autorep:${TRAVIS_BRANCH} .;
    docker tag $(docker images -q dabelenda/autorep:${TRAVIS_BRANCH}) dabelenda/autorep:latest
  - install -r requirements.txt

script:
  - python -m unittest discover

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u="${TRAVIS_SECRET_DOCKER_USERNAME}" -p="${TRAVIS_SECRET_DOCKER_PASSWORD}";
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        docker push dabelenda/autorep:latest;
      else
        docker push dabelenda/autorep:${TRAVIS_BRANCH};
      fi;
      docker logout;
    fi
